### PR TITLE
Make tests compilable on macOS

### PR DESCRIPTION
**Pull request by zayass**
Also include hook for using precompiled native dependencies sqlite/libxml etc

### CODE REVIEW

**Comment by zayass** [comment]
Example of prebuilt library module layout https://github.com/zayass/swift-android-libxml-prebuilt

**Comment by johnno1962** [comment]
These library modules are interesting. I’d really like to see a modulemap for sqlite. These could be included in the distribution.

**Comment by zayass** [comment]
It will look almost the same. public headers in include/ prebuilt .so in libs, modulemap and Package.swift to link them together.

**Comment by johnno1962** [comment]
So you need to include a .so for swift to link against in swift-install/usr/lib/swift/android but it will use the android supplied one?

**Comment by zayass** [comment]
or you can provide them within package like here https://github.com/zayass/swift-android-libxml-prebuilt/tree/master/libs
About Android provided so, I don't know but sounds very similar to issues. So maybe can be solved in the same way.
If Android provided .so is ok you can just use it.


Abd I think static libraries should work in same way

**Comment by zayass** [comment]
Script for running tests added

**Pull request merged**
