### PR TITLE
macOS XCTest

### PR DESCRIPTION
**Pull request by zayass**
fixes for #2

### CODE REVIEW

**Comment by johnno1962** [comment]
Thanks. Everything checks out this end. There is an extra newline leaking in somewhere but thats not a big deal.
```
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJavaWithJavac UP-TO-DATE
:compileSwift

:copySwiftStdlib
:copySwift UP-TO-DATE
:compileDebugNdk UP-TO-DATE
:compileDebugSources UP-TO-DATE
:transformClassesWithDexForDebug UP-TO-DATE
```

**Comment by zayass** [comment]
@johnno1962 are you plan to merge this to master?

**Comment by johnno1962** [comment]
Yes, let me sleep on it and it will probably go in tomorrow.

**Comment by zayass** [comment]
:) If you want merge incoming to master on your side roll back master firstly to avoid conflicts

**Pull request merged**
